<template>
  <div id="page">
    <div :class="isFocus?'noFocus source':' source'">
      <el-alert type="info" show-icon :closable="false" class="noGrow">
        默认配置文件位置：<span>/etc/fancontrol</span>
      </el-alert>
      <el-input
          v-model="inputText"
          type="textarea"
          placeholder="原始文件"
          resize="none"
      />
    </div>
    <div class="connect">
      <el-button v-if="isFocus===false" @click="isFocus=!isFocus"><el-icon><DArrowLeft /></el-icon></el-button>
      <el-button v-else @click="isFocus=!isFocus"><el-icon><DArrowRight /></el-icon></el-button>

      <el-button @click="parseToGUI()"><el-icon><ArrowRightBold /></el-icon> <el-icon><View /></el-icon></el-button>
      <el-button @click="guiToText()"><el-icon><EditPen /></el-icon><el-icon><ArrowLeftBold /></el-icon></el-button>

    </div>
    <EditGUI class="gui" v-model:gui-data="guiData" />
  </div>
</template>

<script>
import {computed} from "vue";
import EditGUI from "./components/EditGUI.vue";
import {ArrowLeftBold, ArrowRightBold, DArrowLeft, DArrowRight, EditPen, View} from "@element-plus/icons-vue";

export default {
  name: "app",
  //引入模块
  components: {
    EditPen,
    DArrowRight,
    DArrowLeft,
    ArrowRightBold,
    ArrowLeftBold,
    EditGUI,
    View
  },
  data() {
    return {
      inputText: "# Configuration file generated by pwmconfig, changes will be lost\n" +
          "INTERVAL=10\n" +
          "DEVPATH=hwmon1=devices/platform/coretemp.0 hwmon2=devices/platform/nct6775.656\n" +
          "DEVNAME=hwmon1=coretemp hwmon2=nct6793\n" +
          "FCTEMPS= hwmon2/pwm2=hwmon1/temp1_input\n" +
          "FCFANS= hwmon2/pwm2=hwmon2/fan2_input\n" +
          "MINTEMP= hwmon2/pwm2=40\n" +
          "MAXTEMP= hwmon2/pwm2=70\n" +
          "MINSTART= hwmon2/pwm2=45\n" +
          "MINSTOP= hwmon2/pwm2=30\n" +
          "MINPWM=hwmon2/pwm2=0\n" +
          "MAXPWM=hwmon2/pwm2=255",
      isFocus: false,

      guiData: {
        tmpSourceData: {
          DEVNAME: [],
          INTERVAL:[],
          DEVPATH:[],
          FCTEMPS:[],
          FCFANS:[],
          MINTEMP:[],
          MAXTEMP:[],
          MINSTART:[],
          MINSTOP:[],
          MINPWM:[],
          MAXPWM:[]
        },
        Fan: {
          // "hwmon2/pwm1": {},
          // "hwmon2/pwm2": {},
          // "hwmon2/pwm3": {},
          // "hwmon2/pwm4": {},
        },
        dev: {},
        INTERVAL: 0,
      },
    }
  },
  //方法
  methods: {
    parseToGUI: function (inputText=this.inputText) {
      // let tmpData = {}
      let that = this;
      this.guiData.tmpSourceData = {};
      this.guiData.Fan = {};
      this.guiData.dev = {};

      let lines = inputText
          .replaceAll("\r\n", "\n")
          .replaceAll("\r", "\n")
          .split("\n");

      let findData = function (text) {
        if(!text || text.indexOf("#")>=0){
          return
        }
        let kdv = text.indexOf("=");
        if (kdv===-1){
          return;
        }
        let key = text.substring(0, kdv);
        let vals = text.substring(kdv+1);
        vals = vals.trim()

        let checkFan = function (text, data) {
          for (const one of text) {
            let dev_KaV = one.split("=");
            if(!that.guiData.Fan[dev_KaV[0]]){
              that.guiData.Fan[dev_KaV[0]] = {}
            }
            that.guiData.Fan[dev_KaV[0]][data] = dev_KaV[1]
          }
        }

        let many = vals.split(" ");
        switch (key) {
          // 识别物理传感器
          case "DEVNAME":
            for (const one of many) {
              let dev_KaV = one.split("=");
              if(dev_KaV.length>1){
                if(!that.guiData.dev[dev_KaV[0]]){
                  that.guiData.dev[dev_KaV[0]] = {}
                }
                that.guiData.dev[dev_KaV[0]].name = dev_KaV[1];
              }
            }
            break;
          case "DEVPATH":
            for (const one of many) {
              let dev_KaV = one.split("=");
              if(dev_KaV.length>1){
                if(!that.guiData.dev[dev_KaV[0]]){
                  that.guiData.dev[dev_KaV[0]] = {}
                }
                that.guiData.dev[dev_KaV[0]].path = dev_KaV[1];
              }
            }
            break;
          // 识别风扇
          case "FCFANS":
            // for (const one of many) {
            //   let dev_KaV = one.split("=");
            //   if(!that.guiData.dev[dev_KaV[0]]){
            //     that.guiData.dev[dev_KaV[0]] = {}
            //   }
            // }
            checkFan(many, "FCFANS")
            break;
          case "FCTEMPS":
            checkFan(many, "FCTEMPS")
            break;
          case "MAXPWM":
            checkFan(many, "MAXPWM")
            break;
          case "MAXTEMP":
            checkFan(many, "MAXTEMP")
            break;
          case "MINPWM":
            checkFan(many, "MINPWM")
            break;
          case "MINSTART":
            checkFan(many, "MINSTART")
            break;
          case "MINSTOP":
            checkFan(many, "MINSTOP")
            break;
          case "MINTEMP":
            checkFan(many, "MINTEMP")
            break;
          case "INTERVAL":
            that.guiData.INTERVAL = parseInt(vals.trim())
            break;
          // default:
        }

        if(vals.indexOf(" ")===-1){
          that.guiData.tmpSourceData[key] = [vals]
        }else{
          that.guiData.tmpSourceData[key] = many
        }


      }
      for (const line of lines) {
        findData(line)
      }

      console.log("parseToGUI", that.guiData)

      // for (let i = 0; i < this.guiData.tmpSourceData.FCFANS.length; i++) {
      //   const fan = this.guiData.tmpSourceData.FCFANS[i]
      //
      //   let con = {
      //     // 风扇路径
      //     FCFANS: "",
      //     // 读取传感器的温度
      //     FCTEMPS: "",
      //     // 低于多少度时处于最小速度
      //     MINTEMP: 0,
      //     // 高于多少度时处于最大速度
      //     MAXTEMP: 0,
      //     // 最大转速(0~255)
      //     MAXPWM: 0,
      //
      //     //
      //     MINSTOP: 0,
      //
      //     //
      //     MINSTART: 0,
      //
      //     //
      //     MINPWM: 0,
      //   }
      //   // this.guiData.Fan
      // }

    },

    guiToText: function () {
      let tmp = "# Configuration file generated by Fancontrol-Edit at " + new Date();
      tmp += "\r\n";

      console.log(this.guiData)

      tmp += "INTERVAL=" + this.guiData.INTERVAL
      tmp += "\r\n";

      let DEVPATH = ""
      let DEVNAME = ""
      for (const devName of Object.keys(this.guiData.dev)) {
        DEVPATH += devName + "=" + this.guiData.dev[devName].path + " "
        DEVNAME += devName + "=" + this.guiData.dev[devName].name + " "
      }
      tmp += "DEVPATH=" + DEVPATH + "\r\n"
      tmp += "DEVNAME=" + DEVNAME + "\r\n"

      let FCTEMPS="", FCFANS="", MINTEMP="", MAXTEMP="", MINSTART="", MINSTOP="", MINPWM="", MAXPWM=""
      for (const fn of Object.keys(this.guiData.Fan)) {
        const fan = this.guiData.Fan[fn];
        if(fan.FCTEMPS  || fan.FCTEMPS  ===0){FCTEMPS  += fn + "=" + fan.FCTEMPS  + " "}
        if(fan.FCFANS   || fan.FCFANS   ===0){FCFANS   += fn + "=" + fan.FCFANS   + " "}
        if(fan.MINTEMP  || fan.MINTEMP  ===0){MINTEMP  += fn + "=" + fan.MINTEMP  + " "}
        if(fan.MAXTEMP  || fan.MAXTEMP  ===0){MAXTEMP  += fn + "=" + fan.MAXTEMP  + " "}
        if(fan.MINSTART || fan.MINSTART ===0){MINSTART += fn + "=" + fan.MINSTART + " "}
        if(fan.MINSTOP  || fan.MINSTOP  ===0){MINSTOP  += fn + "=" + fan.MINSTOP  + " "}
        if(fan.MINPWM   || fan.MINPWM   ===0){MINPWM   += fn + "=" + fan.MINPWM   + " "}
        if(fan.MAXPWM   || fan.MAXPWM   ===0){MAXPWM   += fn + "=" + fan.MAXPWM   + " "}
      }
      tmp += "FCTEMPS= " + FCTEMPS + "\r\n"
      tmp += "FCFANS= " + FCFANS + "\r\n"
      tmp += "MINTEMP= " + MINTEMP + "\r\n"
      tmp += "MAXTEMP= " + MAXTEMP + "\r\n"
      tmp += "MINSTART= " + MINSTART + "\r\n"
      tmp += "MINSTOP= " + MINSTOP + "\r\n"
      tmp += "MINPWM= " + MINPWM + "\r\n"
      tmp += "MAXPWM= " + MAXPWM + "\r\n"

      console.log(tmp)
      this.inputText = tmp
    }
  },
  //启动事件
  mounted() {
  },
  //销毁
  beforeUnmount() {
  }
}
</script>

<style>
*{
  margin: 0;
  padding: 0;
}
body, html{
  width: 100%;
  height: 100%;
}
#app{
  width: 100%;
  height: 100%;
}

.flexBox{
  display: flex;
  grid-gap: 1rem;
  gap: 1rem;
}
</style>

<style scoped lang="scss">
div{
  display: flex;
  flex-grow: 1;
}
.noGrow{
  flex-grow: 0;
}

#page{
  width: 100%;
  height: 100%;
  display: flex;

  &>div{
    flex-grow: 1;
    margin: 1rem 1rem 1rem 1rem;
  }
  .source{
    margin-right: 0;
    width: 100%;

    transition: 0.5s;
    flex-direction: column;
    gap: 0.5rem;
  }
  .source.noFocus{
    width: 2rem;
    flex-grow: 0;
  }
  .connect{
    width: 1rem;
    flex-shrink: 0;
    flex-grow: 0;

    flex-direction: column;
    justify-content: center;

    button{
      margin: 0.5rem 0 0 0;
    }
    button:first-child{
      margin-top: 0;
    }
  }
  .gui{
    width: 50%;
  }
}

</style>
